import { TODAY_JSON_URL } from './config.js';

/**
 * Today's date in YYYY-MM-DD format, anchored to Boston (America/New_York).
 * Used to detect when today.json is stale (e.g. the action hasn't run yet
 * after midnight rolled over).
 */
export function getBostonDateString(date = new Date()) {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/New_York',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(date);
}

/**
 * Pretty-print today's date for display (e.g. "Tuesday, April 28").
 */
export function getDisplayDate(date = new Date()) {
  return new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/New_York',
    weekday: 'long',
    month: 'long',
    day: 'numeric',
  }).format(date);
}

/**
 * Fetch today.json (generated by the GitHub Action).
 *
 * Returns:
 *   { date, found, meal, error, generated_at, isStale }
 *
 * - `isStale` is true when the file's date doesn't match today's Boston date,
 *   meaning the action probably hasn't run for today yet.
 */
export async function fetchTodayResult() {
  // Cache-bust so we don't get yesterday's file from the CDN.
  const url = `${TODAY_JSON_URL}?t=${Date.now()}`;
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) {
    throw new Error(`couldn't load today.json (${res.status})`);
  }
  const data = await res.json();
  data.isStale = data.date !== getBostonDateString();
  return data;
}
